apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: fp
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30000
