apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: ecrcred
      containers:
        - name: webapp
          image: 998727131331.dkr.ecr.us-east-1.amazonaws.com/clo835fp-web:latest
          ports:
            - containerPort: 81
          envFrom:
            - secretRef:
                name: app-secrets       
            - configMapRef:
                name: app-config         
          env:
            - name: DBHOST
              value: "mysql"
            - name: DBUSER
              value: "root"
            - name: DBPORT
              value: "3306"
