apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecrcred
      containers:
        - name: mysql
          image: 998727131331.dkr.ecr.us-east-1.amazonaws.com/clo835fp-mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
