apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
