apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: fp
subjects:
- kind: ServiceAccount
  name: clo835-sa
  namespace: fp
roleRef:
  kind: Role
  name: clo835
  apiGroup: rbac.authorization.k8s.io